// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abtloqqhlrjpamiuyjer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFidGxvcXFobHJqcGFtaXV5amVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODIyNzEsImV4cCI6MjA2MzY1ODI3MX0.5_y4MuhniZxdPQjw4UHOhBtweCqFHrzvaQlC4_8kgTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);